bookwyrm/urls.py
""" url routing for the app and api """
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from bookwyrm import settings, views
from bookwyrm.utils import regex

USER_PATH = rf"^user/(?P<username>{regex.USERNAME})"
LOCAL_USER_PATH = rf"^user/(?P<username>{regex.LOCALNAME})"

status_types = [
    "status",
    "review",
    "reviewrating",
    "comment",
    "quotation",
    "boost",
    "generatednote",
]

STATUS_TYPES_STRING = "|".join(status_types)
STATUS_PATH = rf"{USER_PATH}/({STATUS_TYPES_STRING})/(?P<status_id>\d+)"

BOOK_PATH = r"^book/(?P<book_id>\d+)"

STREAMS = "|".join(s["key"] for s in settings.STREAMS)

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # federation endpoints
    re_path(r"^inbox/?$", views.Inbox.as_view()),
    re_path(rf"{LOCAL_USER_PATH}/inbox/?$", views.Inbox.as_view()),
    re_path(rf"{LOCAL_USER_PATH}/outbox/?$", views.Outbox.as_view()),
    re_path(r"^\.well-known/webfinger/?$", views.webfinger),
    re_path(r"^\.well-known/nodeinfo/?$", views.nodeinfo_pointer),
    re_path(r"^\.well-known/host-meta/?$", views.host_meta),
    re_path(r"^nodeinfo/2\.0/?$", views.nodeinfo),
    re_path(r"^api/v1/instance/?$", views.instance_info),
    re_path(r"^api/v1/instance/peers/?$", views.peers),
    re_path(r"^opensearch.xml$", views.opensearch, name="opensearch"),
    # polling updates
    re_path("^api/updates/notifications/?$", views.get_notification_count),
    re_path("^api/updates/stream/(?P<stream>[a-z]+)/?$", views.get_unread_status_count),
    # authentication
    re_path(r"^login/?$", views.Login.as_view(), name="login"),
    re_path(r"^login/(?P<confirmed>confirmed)?$", views.Login.as_view(), name="login"),
    re_path(r"^register/?$", views.Register.as_view()),
    re_path(r"confirm-email/?$", views.ConfirmEmail.as_view(), name="confirm-email"),
    re_path(
        r"confirm-email/(?P<code>[A-Za-z0-9]+)/?$",
        views.ConfirmEmailCode.as_view(),
        name="confirm-email-code",
    ),
    re_path(r"^resend-link/?$", views.resend_link, name="resend-link"),
    re_path(r"^logout/?$", views.Logout.as_view(), name="logout"),
    re_path(
        r"^password-reset/?$",
        views.PasswordResetRequest.as_view(),
        name="password-reset",
    ),
    re_path(
        r"^password-reset/(?P<code>[A-Za-z0-9]+)/?$", views.PasswordReset.as_view()
    ),
    # admin
    re_path(
        r"^settings/dashboard/?$", views.Dashboard.as_view(), name="settings-dashboard"
    ),
    re_path(r"^settings/site-settings/?$", views.Site.as_view(), name="settings-site"),
    re_path(
        r"^settings/announcements/?$",
        views.Announcements.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/?$",
        views.Announcement.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/delete/?$",
        views.delete_announcement,
        name="settings-announcements-delete",
    ),
    re_path(
        r"^settings/email-preview/?$",
        views.admin.site.email_preview,
        name="settings-email-preview",
    ),
    re_path(
        r"^settings/users/?$", views.UserAdminList.as_view(), name="settings-users"
    ),
    re_path(
        r"^settings/users/(?P<user>\d+)/?$",
        views.UserAdmin.as_view(),
        name="settings-user",
    ),
    re_path(
        r"^settings/federation/(?P<status>(federated|blocked))?/?$",
        views.Federation.as_view(),
        name="settings-federation",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/?$",
        views.FederatedServer.as_view(),
        name="settings-federated-server",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/block?$",
        views.block_server,
        name="settings-federated-server-block",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/unblock?$",
        views.unblock_server,
        name="settings-federated-server-unblock",
    ),
    re_path(
        r"^settings/federation/add/?$",
        views.AddFederatedServer.as_view(),
        name="settings-add-federated-server",
    ),
    re_path(
        r"^settings/federation/import/?$",
        views.ImportServerBlocklist.as_view(),
        name="settings-import-blocklist",
    ),
    re_path(
        r"^settings/invites/?$", views.ManageInvites.as_view(), name="settings-invites"
    ),
    re_path(
        r"^settings/requests/?$",
        views.ManageInviteRequests.as_view(),
        name="settings-invite-requests",
    ),
    re_path(
        r"^settings/requests/ignore?$",
        views.ignore_invite_request,
        name="settings-invite-requests-ignore",
    ),
    re_path(
        r"^invite-request/?$", views.InviteRequest.as_view(), name="invite-request"
    ),
    re_path(r"^invite/(?P<code>[A-Za-z0-9]+)/?$", views.Invite.as_view()),
    re_path(
        r"^settings/email-blocklist/?$",
        views.EmailBlocklist.as_view(),
        name="settings-email-blocks",
    ),
    re_path(
        r"^settings/email-blocks/(?P<domain_id>\d+)/delete/?$",
        views.EmailBlocklist.as_view(),
        name="settings-email-blocks-delete",
    ),
    re_path(
        r"^settings/ip-blocklist/?$",
        views.IPBlocklist.as_view(),
        name="settings-ip-blocks",
    ),
    re_path(
        r"^settings/ip-blocks/(?P<block_id>\d+)/delete/?$",
        views.IPBlocklist.as_view(),
        name="settings-ip-blocks-delete",
    ),
    # moderation
    re_path(r"^settings/reports/?$", views.Reports.as_view(), name="settings-reports"),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/?$",
        views.Report.as_view(),
        name="settings-report",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/suspend/?$",
        views.suspend_user,
        name="settings-report-suspend",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/unsuspend/?$",
        views.unsuspend_user,
        name="settings-report-unsuspend",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/delete/?$",
        views.moderator_delete_user,
        name="settings-delete-user",
    ),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/resolve/?$",
        views.resolve_report,
        name="settings-report-resolve",
    ),
    re_path(r"^report/?$", views.make_report, name="report"),
    # landing pages
    re_path(r"^about/?$", views.About.as_view(), name="about"),
    path("", views.Home.as_view(), name="landing"),
    re_path(r"^discover/?$", views.Discover.as_view(), name="discover"),
    re_path(r"^notifications/?$", views.Notifications.as_view(), name="notifications"),
    re_path(
        r"^notifications/(?P<notification_type>mentions)/?$",
        views.Notifications.as_view(),
        name="notifications",
    ),
    re_path(r"^directory/?", views.Directory.as_view(), name="directory"),
    # Get started
    re_path(
        r"^get-started/profile/?$",
        views.GetStartedProfile.as_view(),
        name="get-started-profile",
    ),
    re_path(
        r"^get-started/books/?$",
        views.GetStartedBooks.as_view(),
        name="get-started-books",
    ),
    re_path(
        r"^get-started/users/?$",
        views.GetStartedUsers.as_view(),
        name="get-started-users",
    ),
    # feeds
    re_path(rf"^(?P<tab>{STREAMS})/?$", views.Feed.as_view()),
    re_path(
        r"^direct-messages/?$", views.DirectMessage.as_view(), name="direct-messages"
    ),
    re_path(
        rf"^direct-messages/(?P<username>{regex.USERNAME})?$",
        views.DirectMessage.as_view(),
        name="direct-messages-user",
    ),
    # search
    re_path(r"^search.json/?$", views.Search.as_view(), name="search"),
    re_path(r"^search/?$", views.Search.as_view(), name="search"),
    # imports
    re_path(r"^import/?$", views.Import.as_view(), name="import"),
    re_path(
        r"^import/(?P<job_id>\d+)/?$",
        views.ImportStatus.as_view(),
        name="import-status",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/retry/(?P<item_id>\d+)/?$",
        views.retry_item,
        name="import-item-retry",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/failed/?$",
        views.ImportTroubleshoot.as_view(),
        name="import-troubleshoot",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/?$",
        views.ImportManualReview.as_view(),
        name="import-review",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/?$",
        views.ImportManualReview.as_view(),
        name="import-review",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/(?P<item_id>\d+)/approve/?$",
        views.approve_import_item,
        name="import-approve",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/(?P<item_id>\d+)/delete/?$",
        views.delete_import_item,
        name="import-delete",
    ),
    # users
    re_path(rf"{USER_PATH}\.json$", views.User.as_view()),
    re_path(rf"{USER_PATH}/?$", views.User.as_view(), name="user-feed"),
    re_path(rf"{USER_PATH}/rss/?$", views.rss_feed.RssFeed(), name="user-rss"),
    re_path(
        rf"{USER_PATH}/followers(.json)?/?$",
        views.Followers.as_view(),
        name="user-followers",
    ),
    re_path(
        rf"{USER_PATH}/following(.json)?/?$",
        views.Following.as_view(),
        name="user-following",
    ),
    re_path(r"^hide-suggestions/?$", views.hide_suggestions, name="hide-suggestions"),
    # groups
    re_path(rf"{USER_PATH}/groups/?$", views.UserGroups.as_view(), name="user-groups"),
    re_path(
        r"^group/(?P<group_id>\d+)(.json)?/?$", views.Group.as_view(), name="group"
    ),
    re_path(

celerywyrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from celerywyrm import settings

urlpatterns = [
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookwyrm/models/announcement.py
""" admin announcements """
from django.db import models
from django.db.models import Q
from django.utils import timezone

from .base_model import BookWyrmModel


class Announcement(BookWyrmModel):
    """The admin has something to say"""

    user = models.ForeignKey("User", on_delete=models.PROTECT)
    preview = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    event_date = models.DateTimeField(blank=True, null=True)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=True)

    @classmethod
    def active_announcements(cls):
        """announcements that should be displayed"""
        now = timezone.now()
        return cls.objects.filter(
            Q(start_date__isnull=True) | Q(start_date__lte=now),
            Q(end_date__isnull=True) | Q(end_date__gte=now),
            active=True,
        )

bookwyrm/models/antispam.py
""" Lets try NOT to sell viagra """
from django.db import models

from .user import User


class EmailBlocklist(models.Model):
    """blocked email addresses"""

    created_date = models.DateTimeField(auto_now_add=True)
    domain = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        """default sorting"""

        ordering = ("-created_date",)

    @property
    def users(self):
        """find the users associated with this address"""
        return User.objects.filter(email__endswith=f"@{self.domain}")


class IPBlocklist(models.Model):
    """blocked ip addresses"""

    created_date = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        """default sorting"""

        ordering = ("-created_date",)

bookwyrm/models/attachment.py
""" media that is posted in the app """
from django.db import models

from bookwyrm import activitypub
from .activitypub_mixin import ActivitypubMixin
from .base_model import BookWyrmModel
from . import fields


class Attachment(ActivitypubMixin, BookWyrmModel):
    """an image (or, in the future, video etc) associated with a status"""

    status = models.ForeignKey(
        "Status", on_delete=models.CASCADE, related_name="attachments", null=True
    )
    reverse_unfurl = True

    class Meta:
        """one day we'll have other types of attachments besides images"""

        abstract = True


class Image(Attachment):
    """an image attachment"""

    image = fields.ImageField(
        upload_to="status/",
        null=True,
        blank=True,
        activitypub_field="url",
        alt_field="caption",
    )
    caption = fields.TextField(null=True, blank=True, activitypub_field="name")

    activity_serializer = activitypub.Document

bookwyrm/models/author.py
""" database schema for info about authors """
from django.contrib.postgres.indexes import GinIndex
from django.db import models

from bookwyrm import activitypub
from bookwyrm.settings import DOMAIN

from .book import BookDataModel
from . import fields


class Author(BookDataModel):
    """basic biographic info"""

    wikipedia_link = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    isni = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    viaf_id = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    gutenberg_id = fields.CharField(
        max_length=255, blank=True, null=True, deduplication_field=True
    )
    # idk probably other keys would be useful here?
    born = fields.DateTimeField(blank=True, null=True)
    died = fields.DateTimeField(blank=True, null=True)
    name = fields.CharField(max_length=255)
    aliases = fields.ArrayField(
        models.CharField(max_length=255), blank=True, default=list
    )
    bio = fields.HtmlField(null=True, blank=True)

    def get_remote_id(self):
        """editions and works both use "book" instead of model_name"""
        return f"https://{DOMAIN}/author/{self.id}"

    activity_serializer = activitypub.Author

    class Meta:
        """sets up postgres GIN index field"""

        indexes = (GinIndex(fields=["search_vector"]),)

bookwyrm/models/federated_server.py
""" connections to external ActivityPub servers """
from urllib.parse import urlparse

from django.apps import apps
from django.db import models
from django.utils.translation import gettext_lazy as _

from .base_model import BookWyrmModel

FederationStatus = [
    ("federated", _("Federated")),
    ("blocked", _("Blocked")),
]


class FederatedServer(BookWyrmModel):
    """store which servers we federate with"""

    server_name = models.CharField(max_length=255, unique=True)
    status = models.CharField(
        max_length=255, default="federated", choices=FederationStatus
    )
    # is it mastodon, bookwyrm, etc
    application_type = models.CharField(max_length=255, null=True, blank=True)
    application_version = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def block(self):
        """block a server"""
        self.status = "blocked"
        self.save(update_fields=["status"])

        # deactivate all associated users
        self.user_set.filter(is_active=True).update(
            is_active=False, deactivation_reason="domain_block"
        )

        # check for related connectors
        if self.application_type == "bookwyrm":
            connector_model = apps.get_model("bookwyrm.Connector", require_ready=True)
            connector_model.objects.filter(
                identifier=self.server_name, active=True
            ).update(active=False, deactivation_reason="domain_block")

    def unblock(self):
        """unblock a server"""
        self.status = "federated"
        self.save(update_fields=["status"])

        self.user_set.filter(deactivation_reason="domain_block").update(
            is_active=True, deactivation_reason=None
        )

        # check for related connectors
        if self.application_type == "bookwyrm":
            connector_model = apps.get_model("bookwyrm.Connector", require_ready=True)
            connector_model.objects.filter(
                identifier=self.server_name,
                active=False,
                deactivation_reason="domain_block",
            ).update(active=True, deactivation_reason=None)

    @classmethod
    def is_blocked(cls, url):
        """look up if a domain is blocked"""
        url = urlparse(url)
        domain = url.netloc
        return cls.objects.filter(server_name=domain, status="blocked").exists()

bookwyrm/templates/settings/federation/edit_instance.html
{% extends 'settings/layout.html' %}
{% load i18n %}
{% block title %}{% trans "Add instance" %}{% endblock %}

{% block header %}
{% trans "Add instance" %}
<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to instance list" %}</a>
{% endblock %}

{% block panel %}

<div class="tabs">
    <ul>
        {% url 'settings-import-blocklist' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Import block list" %}</a>
        </li>
        {% url 'settings-add-federated-server' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Add instance" %}</a>
        </li>
    </ul>
</div>

<form method="POST" action="{% url 'settings-add-federated-server' %}">
    {% csrf_token %}
    <div class="columns">
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_server_name">{% trans "Instance:" %}</label>
                <input type="text" name="server_name" maxlength="255" class="input" required id="id_server_name" value="{{ form.server_name.value|default:'' }}" placeholder="domain.com">
                {% for error in form.server_name.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_status">{% trans "Status:" %}</label>
                <div class="select">
                    <select name="status" class="" id="id_status">
                        <option value="federated" {% if form.status.value == "federated" %}selected=""{% endif %}>{% trans "Federated" %}</option>
                        <option value="blocked" {% if form.status.value == "blocked" or not form.status.value %}selected{% endif %}>{% trans "Blocked" %}</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="columns">
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_application_type">{% trans "Software:" %}</label>
                <input type="text" name="application_type" maxlength="255" class="input" id="id_application_type" value="{{ form.application_type.value|default:'' }}">
                {% for error in form.application_type.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label" for="id_application_version">{% trans "Version:" %}</label>
                <input type="text" name="application_version" maxlength="255" class="input" id="id_application_version" value="{{ form.application_version.value|default:'' }}">
                {% for error in form.application_version.errors %}
                <p class="help is-danger">{{ error | escape }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="field">
        <label class="label" for="id_notes">{% trans "Notes:" %}</label>
        <textarea name="notes" cols="40" rows="5" class="textarea" id="id_notes">{{ form.notes.value|default:'' }}</textarea>
    </div>

    <button type="submit" class="button is-primary">{% trans "Save" %}</button>
</form>

{% endblock %}

bookwyrm/templates/settings/federation/instance.html
{% extends 'settings/layout.html' %}
{% load i18n %}
{% load markdown %}

{% block title %}{{ server.server_name }}{% endblock %}

{% block header %}
{{ server.server_name }}

{% if server.status == "blocked" %}<span class="icon icon-x has-text-danger is-size-5" title="{% trans 'Blocked' %}"><span class="is-sr-only">{% trans "Blocked" %}</span></span>
{% endif %}

<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to list" %}</a>
{% endblock %}

{% block panel %}
<div class="columns">
    <section class="column is-half is-flex is-flex-direction-column">
        <h2 class="title is-4">{% trans "Details" %}</h2>
        <div class="box is-flex-grow-1 content">
            <dl>
                <dt class="is-pulled-left mr-5">{% trans "Software:" %}</dt>
                <dd>{{ server.application_type }}</dd>

                <dt class="is-pulled-left mr-5">{% trans "Version:" %}</dt>
                <dd>{{ server.application_version }}</dd>

                <dt class="is-pulled-left mr-5">{% trans "Status:" %}</dt>
                <dd>{{ server.get_status_display }}</dd>
            </dl>
        </div>
    </section>

    <section class="column is-half is-flex is-flex-direction-column">
        <h2 class="title is-4">{% trans "Activity" %}</h2>
        <div class="box is-flex-grow-1 content">
            <dl>
                <dt class="is-pulled-left mr-5">{% trans "Users:" %}</dt>
                <dd>
                    {{ users.count }}
                    {% if server.user_set.count %}(<a href="{% url 'settings-users' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                </dd>

                <dt class="is-pulled-left mr-5">{% trans "Reports:" %}</dt>
                <dd>
                    {{ reports.count }}
                    {% if reports.count %}(<a href="{% url 'settings-reports' %}?server={{ server.server_name }}">{% trans "View all" %}</a>){% endif %}
                </dd>

                <dt class="is-pulled-left mr-5">{% trans "Followed by us:" %}</dt>
                <dd>
                    {{ followed_by_us.count }}
                </dd>

                <dt class="is-pulled-left mr-5">{% trans "Followed by them:" %}</dt>
                <dd>
                    {{ followed_by_them.count }}
                </dd>

                <dt class="is-pulled-left mr-5">{% trans "Blocked by us:" %}</dt>
                <dd>
                    {{ blocked_by_us.count }}
                </dd>
            </dl>
        </div>
    </section>
</div>

<section class="block content">
    <header class="columns is-mobile">
        <div class="column">
            <h2 class="title is-4 mb-0">{% trans "Notes" %}</h2>
        </div>
        <div class="column is-narrow">
            {% trans "Edit" as button_text %}
            {% include 'snippets/toggle/open_button.html' with text=button_text icon_with_text="pencil" controls_text="edit_notes" %}
        </div>
    </header>
    {% trans "<em>No notes</em>" as null_text %}
    <div class="box" id="hide_edit_notes">{{ server.notes|to_markdown|default:null_text|safe }}</div>
    <form class="box is-hidden" method="POST" action="{% url 'settings-federated-server' server.id %}" id="edit_notes">
        {% csrf_token %}
        <p>
            <label class="is-sr-only" for="id_notes">Notes:</label>
            <textarea name="notes" cols="40" rows="5" class="textarea" id="id_notes">{{ server.notes|default:"" }}</textarea>
        </p>
        <button type="submit" class="button is-primary">{% trans "Save" %}</button>
        {% trans "Cancel" as button_text %}
        {% include 'snippets/toggle/close_button.html' with text=button_text controls_text="edit_notes" %}
    </form>
</section>

<section class="block content">
    <h2 class="title is-4">{% trans "Actions" %}</h2>
    {% if server.status != 'blocked' %}
    <form class="block" method="post" action="{% url 'settings-federated-server-block' server.id %}">
        {% csrf_token %}
        <button class="button is-danger">{% trans "Block" %}</button>
        <p class="help">{% trans "All users from this instance will be deactivated." %}</p>
    </form>
    {% else %}
    <form class="block" method="post" action="{% url 'settings-federated-server-unblock' server.id %}">
        {% csrf_token %}
        <button class="button">{% trans "Un-block" %}</button>
        <p class="help">{% trans "All users from this instance will be re-activated." %}</p>
    </form>
    {% endif %}
</section>

{% endblock %}

bookwyrm/templates/settings/federation/instance_blocklist.html
{% extends 'settings/layout.html' %}
{% load i18n %}
{% block title %}{% trans "Add instance" %}{% endblock %}

{% block header %}
{% trans "Import Blocklist" %}
<a href="{% url 'settings-federation' %}" class="has-text-weight-normal help">{% trans "Back to instance list" %}</a>
{% endblock %}

{% block panel %}

<div class="tabs">
    <ul>
        {% url 'settings-import-blocklist' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Import block list" %}</a>
        </li>
        {% url 'settings-add-federated-server' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Add instance" %}</a>
        </li>
    </ul>
</div>

{% if succeeded and not failed %}
<p class="notification is-primary">{% trans "Success!" %}</p>
{% elif succeeded or failed %}
<div class="block content">
    {% if succeeded %}
    <p>{% trans "Successfully blocked:" %} {{ succeeded }}</p>
    {% endif %}
    <p>{% trans "Failed:" %}</p>
    <ul>
        {% for item in failed %}
        <li>
            <pre>
{{ item }}
</pre>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<form method="POST" action="{% url 'settings-import-blocklist' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
        <label class="label" for="id_file">JSON data:</label>
        <aside class="help">
            Expects a json file in the format provided by <a href="https://fediblock.org/" target="_blank" rel="noopener">FediBlock</a>, with a list of entries that have <code>instance</code> and <code>url</code> fields. For example:
            <pre>
[
    {
        "instance": "example.instance.com",
        "url": "https://link.to.more/info"
    },
    ...
]
</pre>
        </aside>
        <input type="file" name="json_file" required="" id="id_file">
    </div>

    <button type="submit" class="button is-primary">{% trans "Import" %}</button>
</form>

{% endblock %}

bookwyrm/templates/settings/federation/instance_list.html
{% extends 'settings/layout.html' %}
{% load i18n %}
{% block title %}{% trans "Federated Instances" %}{% endblock %}

{% block header %}{% trans "Federated Instances" %}{% endblock %}

{% block edit-button %}
<a href="{% url 'settings-import-blocklist' %}">
    <span class="icon icon-plus" title="{% trans 'Add instance' %}" aria-hidden="True"></span>
    <span class="is-hidden-mobile">{% trans "Add instance" %}</span>
</a>
{% endblock %}

{% block panel %}
<div class="tabs">
    <ul>
        {% url 'settings-federation' status='federated' as url %}
        <li {% if request.path in url %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Federated" %}</a>
        </li>
        {% url 'settings-federation' status='blocked' as url %}
        <li {% if url in request.path %}class="is-active" aria-current="page"{% endif %}>
            <a href="{{ url }}">{% trans "Blocked" %}</a>
        </li>
    </ul>
</div>

<table class="table is-striped">
    <tr>
        {% url 'settings-federation' as url %}
        <th>
            {% trans "Instance name" as text %}
            {% include 'snippets/table-sort-header.html' with field="server_name" sort=sort text=text %}
        </th>
        <th>
            {% trans "Date added" as text %}
            {% include 'snippets/table-sort-header.html' with field="created_date" sort=sort text=text %}
        </th>
        <th>
            {% trans "Software" as text %}
            {% include 'snippets/table-sort-header.html' with field="application_type" sort=sort text=text %}
        </th>
        <th>
            {% trans "Users" %}
        </th>
        <th>{% trans "Status" %}</th>
    </tr>
    {% for server in servers %}
    <tr>
        <td><a href="{% url 'settings-federated-server' server.id %}">{{ server.server_name }}</a></td>
        <td>{{ server.created_date }}</td>
        <td>
        {% if server.application_type %}
            {{ server.application_type }}
            {% if server.application_version %}({{ server.application_version }}){% endif %}
        {% endif %}
        </td>
        <td>{{ server.user_set.count }}</td>
        <td>{{ server.get_status_display }}</td>
    </tr>
    {% endfor %}
    {% if not servers %}
    <tr><td colspan="5"><em>{% trans "No instances found" %}</em></td></tr>
    {% endif %}
</table>


{% include 'snippets/pagination.html' with page=servers path=request.path %}
{% endblock %}