bookwyrm/urls.py
""" url routing for the app and api """
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from bookwyrm import settings, views
from bookwyrm.utils import regex

USER_PATH = rf"^user/(?P<username>{regex.USERNAME})"
LOCAL_USER_PATH = rf"^user/(?P<username>{regex.LOCALNAME})"

status_types = [
    "status",
    "review",
    "reviewrating",
    "comment",
    "quotation",
    "boost",
    "generatednote",
]

STATUS_TYPES_STRING = "|".join(status_types)
STATUS_PATH = rf"{USER_PATH}/({STATUS_TYPES_STRING})/(?P<status_id>\d+)"

BOOK_PATH = r"^book/(?P<book_id>\d+)"

STREAMS = "|".join(s["key"] for s in settings.STREAMS)

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # federation endpoints
    re_path(r"^inbox/?$", views.Inbox.as_view()),
    re_path(rf"{LOCAL_USER_PATH}/inbox/?$", views.Inbox.as_view()),
    re_path(rf"{LOCAL_USER_PATH}/outbox/?$", views.Outbox.as_view()),
    re_path(r"^\.well-known/webfinger/?$", views.webfinger),
    re_path(r"^\.well-known/nodeinfo/?$", views.nodeinfo_pointer),
    re_path(r"^\.well-known/host-meta/?$", views.host_meta),
    re_path(r"^nodeinfo/2\.0/?$", views.nodeinfo),
    re_path(r"^api/v1/instance/?$", views.instance_info),
    re_path(r"^api/v1/instance/peers/?$", views.peers),
    re_path(r"^opensearch.xml$", views.opensearch, name="opensearch"),
    # polling updates
    re_path("^api/updates/notifications/?$", views.get_notification_count),
    re_path("^api/updates/stream/(?P<stream>[a-z]+)/?$", views.get_unread_status_count),
    # authentication
    re_path(r"^login/?$", views.Login.as_view(), name="login"),
    re_path(r"^login/(?P<confirmed>confirmed)?$", views.Login.as_view(), name="login"),
    re_path(r"^register/?$", views.Register.as_view()),
    re_path(r"confirm-email/?$", views.ConfirmEmail.as_view(), name="confirm-email"),
    re_path(
        r"confirm-email/(?P<code>[A-Za-z0-9]+)/?$",
        views.ConfirmEmailCode.as_view(),
        name="confirm-email-code",
    ),
    re_path(r"^resend-link/?$", views.resend_link, name="resend-link"),
    re_path(r"^logout/?$", views.Logout.as_view(), name="logout"),
    re_path(
        r"^password-reset/?$",
        views.PasswordResetRequest.as_view(),
        name="password-reset",
    ),
    re_path(
        r"^password-reset/(?P<code>[A-Za-z0-9]+)/?$", views.PasswordReset.as_view()
    ),
    # admin
    re_path(
        r"^settings/dashboard/?$", views.Dashboard.as_view(), name="settings-dashboard"
    ),
    re_path(r"^settings/site-settings/?$", views.Site.as_view(), name="settings-site"),
    re_path(
        r"^settings/announcements/?$",
        views.Announcements.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/?$",
        views.Announcement.as_view(),
        name="settings-announcements",
    ),
    re_path(
        r"^settings/announcements/(?P<announcement_id>\d+)/delete/?$",
        views.delete_announcement,
        name="settings-announcements-delete",
    ),
    re_path(
        r"^settings/email-preview/?$",
        views.admin.site.email_preview,
        name="settings-email-preview",
    ),
    re_path(
        r"^settings/users/?$", views.UserAdminList.as_view(), name="settings-users"
    ),
    re_path(
        r"^settings/users/(?P<user>\d+)/?$",
        views.UserAdmin.as_view(),
        name="settings-user",
    ),
    re_path(
        r"^settings/federation/(?P<status>(federated|blocked))?/?$",
        views.Federation.as_view(),
        name="settings-federation",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/?$",
        views.FederatedServer.as_view(),
        name="settings-federated-server",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/block?$",
        views.block_server,
        name="settings-federated-server-block",
    ),
    re_path(
        r"^settings/federation/(?P<server>\d+)/unblock?$",
        views.unblock_server,
        name="settings-federated-server-unblock",
    ),
    re_path(
        r"^settings/federation/add/?$",
        views.AddFederatedServer.as_view(),
        name="settings-add-federated-server",
    ),
    re_path(
        r"^settings/federation/import/?$",
        views.ImportServerBlocklist.as_view(),
        name="settings-import-blocklist",
    ),
    re_path(
        r"^settings/invites/?$", views.ManageInvites.as_view(), name="settings-invites"
    ),
    re_path(
        r"^settings/requests/?$",
        views.ManageInviteRequests.as_view(),
        name="settings-invite-requests",
    ),
    re_path(
        r"^settings/requests/ignore?$",
        views.ignore_invite_request,
        name="settings-invite-requests-ignore",
    ),
    re_path(
        r"^invite-request/?$", views.InviteRequest.as_view(), name="invite-request"
    ),
    re_path(r"^invite/(?P<code>[A-Za-z0-9]+)/?$", views.Invite.as_view()),
    re_path(
        r"^settings/email-blocklist/?$",
        views.EmailBlocklist.as_view(),
        name="settings-email-blocks",
    ),
    re_path(
        r"^settings/email-blocks/(?P<domain_id>\d+)/delete/?$",
        views.EmailBlocklist.as_view(),
        name="settings-email-blocks-delete",
    ),
    re_path(
        r"^settings/ip-blocklist/?$",
        views.IPBlocklist.as_view(),
        name="settings-ip-blocks",
    ),
    re_path(
        r"^settings/ip-blocks/(?P<block_id>\d+)/delete/?$",
        views.IPBlocklist.as_view(),
        name="settings-ip-blocks-delete",
    ),
    # moderation
    re_path(r"^settings/reports/?$", views.Reports.as_view(), name="settings-reports"),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/?$",
        views.Report.as_view(),
        name="settings-report",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/suspend/?$",
        views.suspend_user,
        name="settings-report-suspend",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/unsuspend/?$",
        views.unsuspend_user,
        name="settings-report-unsuspend",
    ),
    re_path(
        r"^settings/reports/(?P<user_id>\d+)/delete/?$",
        views.moderator_delete_user,
        name="settings-delete-user",
    ),
    re_path(
        r"^settings/reports/(?P<report_id>\d+)/resolve/?$",
        views.resolve_report,
        name="settings-report-resolve",
    ),
    re_path(r"^report/?$", views.make_report, name="report"),
    # landing pages
    re_path(r"^about/?$", views.About.as_view(), name="about"),
    path("", views.Home.as_view(), name="landing"),
    re_path(r"^discover/?$", views.Discover.as_view(), name="discover"),
    re_path(r"^notifications/?$", views.Notifications.as_view(), name="notifications"),
    re_path(
        r"^notifications/(?P<notification_type>mentions)/?$",
        views.Notifications.as_view(),
        name="notifications",
    ),
    re_path(r"^directory/?", views.Directory.as_view(), name="directory"),
    # Get started
    re_path(
        r"^get-started/profile/?$",
        views.GetStartedProfile.as_view(),
        name="get-started-profile",
    ),
    re_path(
        r"^get-started/books/?$",
        views.GetStartedBooks.as_view(),
        name="get-started-books",
    ),
    re_path(
        r"^get-started/users/?$",
        views.GetStartedUsers.as_view(),
        name="get-started-users",
    ),
    # feeds
    re_path(rf"^(?P<tab>{STREAMS})/?$", views.Feed.as_view()),
    re_path(
        r"^direct-messages/?$", views.DirectMessage.as_view(), name="direct-messages"
    ),
    re_path(
        rf"^direct-messages/(?P<username>{regex.USERNAME})?$",
        views.DirectMessage.as_view(),
        name="direct-messages-user",
    ),
    # search
    re_path(r"^search.json/?$", views.Search.as_view(), name="search"),
    re_path(r"^search/?$", views.Search.as_view(), name="search"),
    # imports
    re_path(r"^import/?$", views.Import.as_view(), name="import"),
    re_path(
        r"^import/(?P<job_id>\d+)/?$",
        views.ImportStatus.as_view(),
        name="import-status",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/retry/(?P<item_id>\d+)/?$",
        views.retry_item,
        name="import-item-retry",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/failed/?$",
        views.ImportTroubleshoot.as_view(),
        name="import-troubleshoot",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/?$",
        views.ImportManualReview.as_view(),
        name="import-review",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/?$",
        views.ImportManualReview.as_view(),
        name="import-review",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/(?P<item_id>\d+)/approve/?$",
        views.approve_import_item,
        name="import-approve",
    ),
    re_path(
        r"^import/(?P<job_id>\d+)/review/(?P<item_id>\d+)/delete/?$",
        views.delete_import_item,
        name="import-delete",
    ),
    # users
    re_path(rf"{USER_PATH}\.json$", views.User.as_view()),
    re_path(rf"{USER_PATH}/?$", views.User.as_view(), name="user-feed"),
    re_path(rf"{USER_PATH}/rss/?$", views.rss_feed.RssFeed(), name="user-rss"),
    re_path(
        rf"{USER_PATH}/followers(.json)?/?$",
        views.Followers.as_view(),
        name="user-followers",
    ),
    re_path(
        rf"{USER_PATH}/following(.json)?/?$",
        views.Following.as_view(),
        name="user-following",
    ),
    re_path(r"^hide-suggestions/?$", views.hide_suggestions, name="hide-suggestions"),
    # groups
    re_path(rf"{USER_PATH}/groups/?$", views.UserGroups.as_view(), name="user-groups"),
    re_path(
        r"^group/(?P<group_id>\d+)(.json)?/?$", views.Group.as_view(), name="group"
    ),
    re_path(

celerywyrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

from celerywyrm import settings

urlpatterns = [
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookwyrm/models/connector.py
""" manages interfaces with external sources of book data """
from django.db import models
from bookwyrm.connectors.settings import CONNECTORS

from .base_model import BookWyrmModel, DeactivationReason


ConnectorFiles = models.TextChoices("ConnectorFiles", CONNECTORS)


class Connector(BookWyrmModel):
    """book data source connectors"""

    identifier = models.CharField(max_length=255, unique=True)
    priority = models.IntegerField(default=2)
    name = models.CharField(max_length=255, null=True, blank=True)
    connector_file = models.CharField(max_length=255, choices=ConnectorFiles.choices)
    api_key = models.CharField(max_length=255, null=True, blank=True)
    active = models.BooleanField(default=True)
    deactivation_reason = models.CharField(
        max_length=255, choices=DeactivationReason, null=True, blank=True
    )

    base_url = models.CharField(max_length=255)
    books_url = models.CharField(max_length=255)
    covers_url = models.CharField(max_length=255)
    search_url = models.CharField(max_length=255, null=True, blank=True)
    isbn_search_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.identifier} ({self.id})"

bookwyrm/models/site.py
""" the particulars for this instance of BookWyrm """
import datetime
from urllib.parse import urljoin

from django.db import models, IntegrityError
from django.dispatch import receiver
from django.utils import timezone
from model_utils import FieldTracker

from bookwyrm.preview_images import generate_site_preview_image_task
from bookwyrm.settings import DOMAIN, ENABLE_PREVIEW_IMAGES, STATIC_FULL_URL
from .base_model import BookWyrmModel, new_access_code
from .user import User
from .fields import get_absolute_url


class SiteSettings(models.Model):
    """customized settings for this instance"""

    name = models.CharField(default="BookWyrm", max_length=100)
    instance_tagline = models.CharField(
        max_length=150, default="Social Reading and Reviewing"
    )
    instance_description = models.TextField(default="This instance has no description.")
    instance_short_description = models.CharField(max_length=255, blank=True, null=True)

    # about page
    registration_closed_text = models.TextField(
        default="We aren't taking new users at this time. You can find an open "
        'instance at <a href="https://joinbookwyrm.com/instances">'
        "joinbookwyrm.com/instances</a>."
    )
    invite_request_text = models.TextField(
        default="If your request is approved, you will receive an email with a "
        "registration link."
    )
    code_of_conduct = models.TextField(default="Add a code of conduct here.")
    privacy_policy = models.TextField(default="Add a privacy policy here.")

    # registration
    allow_registration = models.BooleanField(default=True)
    allow_invite_requests = models.BooleanField(default=True)
    require_confirm_email = models.BooleanField(default=True)

    # images
    logo = models.ImageField(upload_to="logos/", null=True, blank=True)
    logo_small = models.ImageField(upload_to="logos/", null=True, blank=True)
    favicon = models.ImageField(upload_to="logos/", null=True, blank=True)
    preview_image = models.ImageField(
        upload_to="previews/logos/", null=True, blank=True
    )

    # footer
    support_link = models.CharField(max_length=255, null=True, blank=True)
    support_title = models.CharField(max_length=100, null=True, blank=True)
    admin_email = models.EmailField(max_length=255, null=True, blank=True)
    footer_item = models.TextField(null=True, blank=True)

    field_tracker = FieldTracker(fields=["name", "instance_tagline", "logo"])

    @classmethod
    def get(cls):
        """gets the site settings db entry or defaults"""
        try:
            return cls.objects.get(id=1)
        except cls.DoesNotExist:
            default_settings = SiteSettings(id=1)
            default_settings.save()
            return default_settings

    @property
    def logo_url(self):
        """helper to build the logo url"""
        return self.get_url("logo", "images/logo.png")

    @property
    def logo_small_url(self):
        """helper to build the logo url"""
        return self.get_url("logo_small", "images/logo-small.png")

    @property
    def favicon_url(self):
        """helper to build the logo url"""
        return self.get_url("favicon", "images/favicon.png")

    def get_url(self, field, default_path):
        """get a media url or a default static path"""
        uploaded = getattr(self, field, None)
        if uploaded:
            return get_absolute_url(uploaded)
        return urljoin(STATIC_FULL_URL, default_path)


class SiteInvite(models.Model):
    """gives someone access to create an account on the instance"""

    created_date = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=32, default=new_access_code)
    expiry = models.DateTimeField(blank=True, null=True)
    use_limit = models.IntegerField(blank=True, null=True)
    times_used = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    invitees = models.ManyToManyField(User, related_name="invitees")

    def valid(self):
        """make sure it hasn't expired or been used"""
        return (self.expiry is None or self.expiry > timezone.now()) and (
            self.use_limit is None or self.times_used < self.use_limit
        )

    @property
    def link(self):
        """formats the invite link"""
        return f"https://{DOMAIN}/invite/{self.code}"


class InviteRequest(BookWyrmModel):
    """prospective users can request an invite"""

    email = models.EmailField(max_length=255, unique=True)
    invite = models.ForeignKey(
        SiteInvite, on_delete=models.SET_NULL, null=True, blank=True
    )
    invite_sent = models.BooleanField(default=False)
    ignored = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        """don't create a request for a registered email"""
        if not self.id and User.objects.filter(email=self.email).exists():
            raise IntegrityError()
        super().save(*args, **kwargs)


def get_passowrd_reset_expiry():
    """give people a limited time to use the link"""
    now = timezone.now()
    return now + datetime.timedelta(days=1)


class PasswordReset(models.Model):
    """gives someone access to create an account on the instance"""

    code = models.CharField(max_length=32, default=new_access_code)
    expiry = models.DateTimeField(default=get_passowrd_reset_expiry)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def valid(self):
        """make sure it hasn't expired or been used"""
        return self.expiry > timezone.now()

    @property
    def link(self):
        """formats the invite link"""
        return f"https://{DOMAIN}/password-reset/{self.code}"


# pylint: disable=unused-argument
@receiver(models.signals.post_save, sender=SiteSettings)
def preview_image(instance, *args, **kwargs):
    """Update image preview for the default site image"""
    if not ENABLE_PREVIEW_IMAGES:
        return
    changed_fields = instance.field_tracker.changed()

    if len(changed_fields) > 0:
        generate_site_preview_image_task.delay()

bookwyrm/templates/settings/layout.html
{% extends 'layout.html' %}
{% load i18n %}

{% block title %}{% trans "Administration" %}{% endblock %}

{% block content %}

<header class="block column is-offset-one-quarter pl-1">
    <div class="columns is-mobile">
        <div class="column">
            <h1 class="title">{% block header %}{% endblock %}</h1>
        </div>
        <div class="column is-narrow">
            {% block edit-button %}{% endblock %}
        </div>
    </div>
</header>

<div class="block columns">
    <nav class="menu column is-one-quarter">
        <h2 class="menu-label">
            {% url 'settings-dashboard' as url %}
            <a
                href="{{ url }}"
                {% if url in request.path %} class="is-active" aria-selected="true"{% endif %}
            >{% trans "Dashboard" %}</a>
        </h2>
        {% if perms.bookwyrm.create_invites %}
        <h2 class="menu-label">{% trans "Manage Users" %}</h2>
        <ul class="menu-list">
            {% if perms.bookwyrm.moderate_user %}
            <li>
                {% url 'settings-users' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Users" %}</a>
            </li>
            {% endif %}
            <li>
                {% url 'settings-invite-requests' as url %}
                {% url 'settings-invites' as alt_url %}
                <a href="{{ url }}"{% if url in request.path or request.path in alt_url %} class="is-active" aria-selected="true"{% endif %}>{% trans "Invites" %}</a>
            </li>
            {% if perms.bookwyrm.control_federation %}
            <li>
                {% url 'settings-federation' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Federated Instances" %}</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
        {% if perms.bookwyrm.moderate_user %}
        <h2 class="menu-label">{% trans "Moderation" %}</h2>
        <ul class="menu-list">
            <li>
                {% url 'settings-reports' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Reports" %}</a>
            </li>
            <li>
                {% url 'settings-email-blocks' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Email Blocklist" %}</a>
            </li>
            <li>
                {% url 'settings-ip-blocks' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "IP Address Blocklist" %}</a>
            </li>
        </ul>
        {% endif %}
        {% if perms.bookwyrm.edit_instance_settings %}
        <h2 class="menu-label">{% trans "Instance Settings" %}</h2>
        <ul class="menu-list">
            <li>
                {% url 'settings-announcements' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Announcements" %}</a>
            </li>
            <li>
                {% url 'settings-site' as url %}
                <a href="{{ url }}"{% if url in request.path %} class="is-active" aria-selected="true"{% endif %}>{% trans "Site Settings" %}</a>
                {% block site-subtabs %}{% endblock %}
            </li>
        </ul>
        {% endif %}
    </nav>
    <div class="column">
        {% block panel %}{% endblock %}
    </div>
</div>

{% endblock %}

bookwyrm/templates/settings/site.html
{% extends 'settings/layout.html' %}
{% load i18n %}

{% block title %}{% trans "Site Settings" %}{% endblock %}

{% block header %}{% trans "Site Settings" %}{% endblock %}

{% block site-subtabs %}
<ul class="menu-list">
    <li><a href="#instance-info">{% trans "Instance Info" %}</a></li>
    <li><a href="#images">{% trans "Images" %}</a></li>
    <li><a href="#footer">{% trans "Footer Content" %}</a></li>
    <li><a href="#registration">{% trans "Registration" %}</a></li>
</ul>
{% endblock %}

{% block panel %}
<form action="{% url 'settings-site' %}" method="POST" class="content" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="block" id="instance_info">
        <h2 class="title is-4">{% trans "Instance Info" %}</h2>
        <div class="box">
            <div class="field">
                <label class="label" for="id_name">{% trans "Instance Name:" %}</label>
                {{ site_form.name }}
            </div>
            <div class="field">
                <label class="label" for="id_instance_tagline">{% trans "Tagline:" %}</label>
                {{ site_form.instance_tagline }}
            </div>
            <div class="field">
                <label class="label" for="id_instance_description">{% trans "Instance description:" %}</label>
                {{ site_form.instance_description }}
            </div>
            <div class="field">
                <label class="label mb-0" for="id_short_description">{% trans "Short description:" %}</label>
                <p class="help">{% trans "Used when the instance is previewed on joinbookwyrm.com. Does not support HTML or Markdown." %}</p>
                {{ site_form.instance_short_description }}
            </div>
            <div class="field">
                <label class="label" for="id_code_of_conduct">{% trans "Code of conduct:" %}</label>
                {{ site_form.code_of_conduct }}
            </div>
            <div class="field">
                <label class="label" for="id_privacy_policy">{% trans "Privacy Policy:" %}</label>
                {{ site_form.privacy_policy }}
            </div>
        </div>
    </section>

    <hr aria-hidden="true">

    <section class="block" id="images">
        <h2 class="title is-4">{% trans "Images" %}</h2>
        <div class="box is-flex">
            <div>
                <label class="label" for="id_logo">{% trans "Logo:" %}</label>
                {{ site_form.logo }}
            </div>
            <div>
                <label class="label" for="id_logo_small">{% trans "Logo small:" %}</label>
                {{ site_form.logo_small }}
            </div>
            <div>
                <label class="label" for="id_favicon">{% trans "Favicon:" %}</label>
                {{ site_form.favicon }}
            </div>
        </div>
    </section>

    <hr aria-hidden="true">

    <section class="block" id="footer">
        <h2 class="title is-4">{% trans "Footer Content" %}</h2>
        <div class="box">
            <div class="field">
                <label class="label" for="id_support_link">{% trans "Support link:" %}</label>
                <input type="text" name="support_link" maxlength="255" class="input" id="id_support_link" placeholder="https://www.patreon.com/bookwyrm"{% if site.support_link %} value="{{ site.support_link  }}"{% endif %}>
            </div>
            <div class="field">
                <label class="label" for="id_support_title">{% trans "Support title:" %}</label>
                <input type="text" name="support_title" maxlength="100" class="input" id="id_support_title" placeholder="Patreon"{% if site.support_title %} value="{{ site.support_title }}"{% endif %}>
            </div>
            <div class="field">
                <label class="label" for="id_admin_email">{% trans "Admin email:" %}</label>
                {{ site_form.admin_email }}
            </div>
            <div class="field">
                <label class="label" for="id_footer_item">{% trans "Additional info:" %}</label>
                {{ site_form.footer_item }}
            </div>
        </div>
    </section>

    <hr aria-hidden="true">

    <section class="block" id="registration">
        <h2 class="title is-4">{% trans "Registration" %}</h2>
        <div class="box">
            <div class="field">
                <label class="label" for="id_allow_registration">
                    {{ site_form.allow_registration }}
                    {% trans "Allow registration" %}
                </label>
            </div>
            <div class="field">
                <label class="label" for="id_allow_invite_requests">
                    {{ site_form.allow_invite_requests }}
                    {% trans "Allow invite requests" %}
                </label>
            </div>
            <div class="field">
                <label class="label mb-0" for="id_require_confirm_email">
                    {{ site_form.require_confirm_email }}
                    {% trans "Require users to confirm email address" %}
                </label>
                <p class="help">{% trans "(Recommended if registration is open)" %}</p>
            </div>
            <div class="field">
                <label class="label" for="id_registration_closed_text">{% trans "Registration closed text:" %}</label>
                {{ site_form.registration_closed_text }}
            </div>
            <div class="field">
                <label class="label" for="id_invite_request_text">{% trans "Invite request text:" %}</label>
                {{ site_form.invite_request_text }}
                {% for error in site_form.invite_request_text.errors %}
                <p class="help is-danger">{{ error|escape }}</p>
                {% endfor %}
            </div>
        </div>
    </section>

    <footer class="block">
        <button class="button is-primary" type="submit">{% trans "Save" %}</button>
    </footer>
</form>
{% endblock %}